---
# Experiment Needs
  dimension: 3
  source_file: "big_cats/lion3.ply"
  target_file: "big_cats/lion6.ply"
  source_name: "lion3"
  target_name: "lion6"
  scale_source: False
  scale_target: False
  warp_source: False
  warp_target: False
  source_scale_amount: 0.8
  target_scale_amount: None
  warp_source_amount: None
  warp_target_amount: [1, 2, 3]
  source_mesh_adjustment: [np.array([[np.cos(180), 0, np.sin(180)],[0, 1, 0],[-np.sin(180), 0, np.cos(180)]]),
  np.array([[np.cos(30), 0, np.sin(30)],[0, 1, 0],[-np.sin(30), 0, np.cos(30)]])]
  target_mesh_adjustment: None
  fps: 1


# Trimesh Needs

  source_landmarks: None
  target_positions:
  steps: [
              [0.01, 10, 0.5, 100000.0],
              [0.02, 5, 0.5, 100000.0],
              [0.03, 2.5, 0.5, 100000.0],
              [0.01, 0, 0.0, 100000.0]
          ]
  eps: 0.0001
  gamma: 1
  distance_threshold: 0.1
  use_faces: True
  use_vertex_normals: True
  neighbors_count: 8